### ISSUE TITLE
Create an example job using the Gmail API and SDK

### ISSUE THREAD

**Issue by D-K-P** [triggerdotdev/api-reference#1]
## Overview:

While we build our official integrations, we want to create examples of how to create jobs which use other APIs with Trigger.dev. This reference will be used in the app on any service we don’t have an integration for yet.

## Details:

In this example, you will build a simple job using the Gmail API and SDK. This will replace the GitHub example we currently have in the app:

![2023-10-18 5](https://github.com/triggerdotdev/api-reference/assets/8297864/4ad54af9-349a-469a-9bec-a0d7e58ae974)

- This job must connect to the [Gmail API](https://developers.google.com/gmail/api/reference/rest), using the [Google Cloud Node SDK](https://developers.google.com/gmail/api/quickstart/nodejs), and return an example payload from the API.
- The job should use an `eventTrigger`
- The job should use `zod` to define the payloads
- Use the structure of our [GitHub API reference file](https://github.com/triggerdotdev/api-reference/blob/main/src/github.ts)

## **Requirements:**

1. Follow [this guide](https://github.com/triggerdotdev/api-reference#setup-how-to-use-this-repo) to get the project setup.
2. Create a new file in the `src` folder, named to match the API (e.g. GitHub would be called `github.ts`).
3. The Trigger.dev client must be defined at the top of the job, with the 'api-reference' id:

```
const client = new TriggerClient({ id: "api-reference" });

```

1. You must add the Express specific lines to the bottom of the Job file:

```
// These lines can be removed if you don't want to use express
import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);

```

1. You must add the new script to the package.json file, in this format:

```
"scripts": {
  //..other scripts
  "<api-name>": "nodemon --watch src/<api name>.ts -r tsconfig-paths/register -r dotenv/config src/<api name>.ts"
}

```

<br />

> [!IMPORTANT]
You must test this Job works before submitting your PR, including a screenshot of a successful run. This may involve you having to setup accounts with services.
>

**Comment by biplobsd** [comment]
@D-K-P  Can I work on this?

**Comment by biplobsd** [comment]
Im working on it ☺️
