### ISSUE TITLE
Create an example job using the X (Twitter) API and SDK

### ISSUE THREAD

**Issue by D-K-P** [triggerdotdev/api-reference#13]
## Overview:

While we build our official integrations, we want to create examples of how to create jobs which use other APIs with Trigger.dev. This reference will be used in the app on any service we don’t have an integration for yet.

## Details:

In this example, you will build a simple job using the X (Twitter) API and SDK. This will replace the GitHub example we currently have in the app:

![2023-10-20 5](https://github.com/triggerdotdev/api-reference/assets/8297864/c837c027-94b8-44a5-a738-73e96b87712e)

- The job must connect to the [X (Twitter) API](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api), using the [SDK](https://developer.twitter.com/en/docs/twitter-api/tools-and-libraries/sdks/overview), and return an example payload from the API.
- The job should use an `eventTrigger`.
- The job should use `zod` to define the payloads.
- Use the structure of our [GitHub API reference file](https://github.com/triggerdotdev/api-reference/blob/main/src/github.ts).

## **Requirements:**

1. Follow [this guide](https://github.com/triggerdotdev/api-reference#setup-how-to-use-this-repo) to get the project setup.
2. Create a new file in the `src` folder, named to match the API (e.g. GitHub would be called `github.ts`).
3. The Trigger.dev client must be defined at the top of the job, with the 'api-reference' id:

```
const client = new TriggerClient({ id: "api-reference" });

```

1. You must add the Express specific lines to the bottom of the Job file:

```
// These lines can be removed if you don't want to use express
import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);

```

1. You must add the new script to the package.json file, in this format:

```
"scripts": {
  //..other scripts
  "<api-name>": "nodemon --watch src/<api name>.ts -r tsconfig-paths/register -r dotenv/config src/<api name>.ts"
}

```

<br />

> [!IMPORTANT]
You must test this Job works before submitting your PR, including a screenshot of a successful run. This may involve you having to setup accounts with services.
>

**Comment by vineetjk** [comment]
lets do it

**Comment by biplobsd** [comment]
@D-K-P 
I tried with `BEARER_TOKEN` on `OAuth2Bearer` but I unable to overwrite the `createTweet` endpoint for use the `OAuth 1.0a` auth.  https://github.com/twitterdev/twitter-api-typescript-sdk/blob/0d12a20a76d6dd9c346decf9cc80bc611975d43f/src/gen/Client.ts#L897C6-L897C31

![image](https://github.com/triggerdotdev/api-reference/assets/43641536/b479f752-dc3c-422d-8ea6-fa127b8828fe)


Here I tried to change the endpoint
![image](https://github.com/triggerdotdev/api-reference/assets/43641536/05d64cfb-4212-4429-8601-bd36eee7eadf)

So now I'm using the axios for direct interact with the path. Now I'm getting this error - 
```
{
  errors: [
    {
      message: 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product',
      code: 453
    }
  ]
}
```

Is it need for pro account?

Here is the code
```typescript
import { TriggerClient, eventTrigger } from "@trigger.dev/sdk";
import z from "zod";
import axios from "axios";

const client = new TriggerClient({
  id: "api-reference",
});

client.defineJob({
  id: "tweet-x",
  name: "Tweet X",
  version: "1.0.0",
  trigger: eventTrigger({
    name: "tweet-x",
    schema: z.object({
      text: z.string(),
    }),
  }),
  run: async (payload, io, ctx) => {
    const { text } = payload;

    // Wrap an SDK call in io.runTask so it's resumable and displays in logs
    await io.runTask(
      "Tweet X",
      async () => {
        try {
          await axios.post(
            "https://api.twitter.com/1.1/statuses/update.json",
            {
              status: text,
            },
            {
              headers: {
                Authorization: `Bearer ${process.env.X_BEARER_TOKEN}`,
                "Content-Type": "application/json",
              },
            }
          );
        } catch (e: any) {
          console.log(e.response.data);
        }
      },

      // Add metadata to the task to improve the display in the logs
      { name: "Tweet X", icon: "twitter" }
    );
  },
});

// These lines can be removed if you don't want to use express
import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);
```

**Comment by gjohnsx** [comment]
@biplobsd  The free tier only allows [OAuth 2.0 with PKCE](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code)
<img width="383" alt="image" src="https://github.com/triggerdotdev/api-reference/assets/93215236/46d8c4a3-3219-4720-a015-148c385ad69d">.

Since OAuth 2.0 with PKCE requires user interaction, this poses a challenge in a background job. 

The Basic tier ($100/month) allows [OAuth 1.0a](https://developer.twitter.com/en/docs/authentication/oauth-1-0a), and the 1.0 endpoint would probably work for a background job.

**Comment by biplobsd** [comment]
Hey @gjohnsx thanks, I did follow this code https://github.com/twitterdev/Twitter-API-v2-sample-code/blob/0d1587147d3bf8338b5fea2b4e5bb56d37f5c2b6/Manage-Tweets/create_tweet.js#L91
