### ISSUE TITLE
Missing define env apiKey in TriggerClient config github example

### ISSUE THREAD

**Issue by biplobsd** [triggerdotdev/api-reference#7]
https://github.com/triggerdotdev/api-reference/blob/ea7f4d7df0fed726c0ab0e609e0d8bd582cf2f0a/src/github.ts#L8C1-L8C59

![image](https://github.com/triggerdotdev/api-reference/assets/43641536/d5a796d3-87f6-4d1a-abf3-facde2a4426b)

**Comment by biplobsd** [comment]
@D-K-P is it missing?

**Comment by biplobsd** [comment]
But somehow client api missing error showing.. I resolved this with passing there.

**Comment by D-K-P** [comment]
That's strange, that shouldn't be the case. Let me know if you have any further issues but I'm going to close this for now.
